"""Reporter agent — turns the decided strategy into a clear, honest proposal.

The system's communication node. Unlike the Profiler and Strategist it produces
FREE TEXT, not structured output, because the deliverable is prose for a human.
Its one job is faithful translation: report what the Strategist decided in plain
language and — critically — carry the suitability note's honesty through to the
user rather than softening it. Runs on the cheap workhorse.

STAGE 7 hardening: if the write-up model fails, we DON'T abort (the allocation is
already built and approved) — we render a plain proposal directly from the
structured Allocation, preserving the suitability note and the disclaimer.
"""
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

from financial_advisor.config import workhorse_llm
from financial_advisor.state import AgentState

REPORTER_SYSTEM_PROMPT = """You are a clear, honest financial communicator. You \
write an investment proposal for a non-expert investor, based ONLY on the strategy \
another agent has already decided. You are the writer, not the strategist: do not \
change the allocation, invent returns, or add recommendations of your own.

Write for a beginner — plain language, no unexplained jargon. Structure it so it's \
easy to follow: open by addressing the investor's request honestly, present the \
recommended allocation with a plain-language reason for each holding, explain what \
they can realistically expect, and lay out the key risks.

Crucial: preserve the honesty of the source material. If the strategy's suitability \
note says the goal is unrealistic, say so clearly and EARLY — do not soften, bury, \
or omit it. Making the proposal pleasant must never cost it its candor. Promise no \
returns.

End with a brief disclaimer: this is an educational illustration generated by an \
automated system, not personalized financial advice, and the investor should \
consult a qualified professional before investing."""


_DISCLAIMER = (
    "Disclaimer: This proposal is an educational illustration generated by an "
    "automated system. It is not personalized financial advice. Investing involves "
    "risk, including possible loss of capital. Consult a qualified financial "
    "professional before making any investment decisions."
)


def _render_fallback_proposal(allocation) -> str:
    """Render a plain proposal directly from the approved Allocation.

    Used only when the write-up model fails: the allocation has already been built
    and approved, so we format it deterministically rather than discard it. Plainer
    than the LLM write-up, but it keeps the suitability note's honesty up front and
    the disclaimer at the end.
    """
    lines = ["Investment Proposal", ""]

    if allocation.suitability_note:               # lead with the honest note
        lines += [allocation.suitability_note, ""]

    lines.append("Proposed allocation:")
    for h in allocation.holdings:
        label = f"{h.asset} ({h.ticker})" if h.ticker else h.asset
        lines.append(f"  - {label} — {h.weight_pct:g}%: {h.rationale}")
    lines.append("")

    if allocation.risk_assessment:
        lines += ["Risk assessment:", allocation.risk_assessment, ""]

    lines.append(_DISCLAIMER)
    return "\n".join(lines)


def reporter_node(state: AgentState) -> dict:
    profile = state["investor_profile"]
    allocation = state["proposed_allocation"]

    try:
        reporter = workhorse_llm(temperature=0.3)    
        response = reporter.invoke([
            SystemMessage(content=REPORTER_SYSTEM_PROMPT),
            HumanMessage(content=(
                f"Investor profile:\n{profile.model_dump()}\n\n"
                f"Decided strategy:\n{allocation.model_dump()}\n\n"
                "Write the proposal now."
            )),
        ])
        proposal = response.content
        return {
            "final_proposal": proposal,
            "messages": [AIMessage(content=f"[Reporter] wrote the final proposal ({len(proposal)} chars).")],
        }
    except Exception as exc:
        # Write-up model failed, but the allocation is already built and approved —
        # render it deterministically rather than throwing the run away.
        proposal = _render_fallback_proposal(allocation)
        return {
            "final_proposal": proposal,
            "messages": [AIMessage(
                content=f"[Reporter] write-up failed ({type(exc).__name__}); "
                        "rendered a plain proposal from the approved allocation."
            )],
        }